FROM python:3.9.12
COPY ./Maggie_Level.py /app/
COPY ./requirements.txt /app/

WORKDIR /app/
RUN mkdir General
RUN mkdir Homer
RUN mkdir Lisa
RUN pip3 install -r ./requeriments.txt

CMD ["python", "Maggie_Level.py"]
